# This configuration file only contains variables for usage with DDEV-local.

vagrant_hostname: afrec.ddev.site

drupal_composer_install_dir: "/var/www/html"
drupal_db_user: db
drupal_db_password: db
drupal_db_name: db
drupal_db_host: db
drupal_mysql_user: db
drupal_mysql_password: db
drupal_site_name: "Drupal"
drupal_install_profile: rain_demo
drupal_account_name: admin
drupal_account_pass: admin

command:
  site:
    options:
      env: true
      multisite: false
      settings_file: settings.local.php
      
project_repo: git@github.com:tcn452/afrec.git
release_repo: ssh://codeserver.dev.cce747c1-5b46-4c21-a55d-7a8f564e99e2@codeserver.dev.cce747c1-5b46-4c21-a55d-7a8f564e99e2.drush.in:2222/~/repository.git afrec-dev
release_drupal_root: web
deploy_host: Pantheon
